# Generated by Django 6.0.3 on 2026-03-12 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPhamChiTiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mau_sac', models.CharField(blank=True, max_length=50)),
                ('kich_co', models.CharField(blank=True, max_length=20)),
                ('so_luong_ton', models.PositiveIntegerField(default=0)),
                ('gia_ban', models.DecimalField(decimal_places=0, max_digits=12, null=True)),
                ('anh', models.ImageField(blank=True, null=True, upload_to='sanpham_chitiet/')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='products.sanpham')),
            ],
            options={
                'verbose_name': 'Chi tiết sản phẩm',
                'verbose_name_plural': 'Chi tiết sản phẩm',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
